In [1]:
!mkdir -p my_package

In [ ]:
%%writefile my_package/__init__.py
# Empty File

Writing my_package/__init__.py


In [2]:
%%writefile my_package/module1.py
def check_prime(num):
    if num == 1:
        print(" prime no")
        return
    if num == 2 or num == 3:
        print("prime no")
        return
    if num % 2 == 0 or num % 3 == 0:
        print("Not prime")
        return

    count = 5 # This assignment is immediately overwritten by the loop variable `count`.
    for count in range(5, num, count + 6):
        if (num % count) == 0 or ((num) % (count + 2) == 0): # Added parentheses for clarity in num % (count+2)
            print("Not prime")
            return
    print("prime no")

def calculate_factorial(num):
    fact = 1
    if num > 0:
        for count in range(1, num + 1):
            fact *= count
        print("\nFactorial of ", num, " is", fact)
    elif num == 0:
        print("\nFactorial of 0 is 1")
    else:
        print("\nPlease enter a non-negative integer !")

Writing my_package/module1.py


In [3]:
%%writefile my_package/module2.py
def add(a, b):
    result = a + b
    return result
def sub(a, b):
    result = a - b
    return result
def mul(a, b):
    result = a * b
    return result
def div(a, b):
    result = a / b
    return result

Writing my_package/module2.py


In [4]:
from my_package import module1 as m
number = int(input("\nEnter number = "))
print(m.check_prime(number))
print(m.calculate_factorial(number))


Enter number = 3
prime no
None

Factorial of  3  is 6
None


In [6]:
from my_package import module2 as m

while True:
    try:
        input_str = input("Enter two numbers separated by a space: ")
        a_str, b_str = input_str.split()
        a = int(a_str)
        b = int(b_str)
        break
    except ValueError:
        print("Invalid input. Please enter two integers separated by a space.")

print(m.add(a,b))
print(m.mul(a,b))

Enter two numbers separated by a space: 2
Invalid input. Please enter two integers separated by a space.
Enter two numbers separated by a space: 12 30
42
360


In [7]:
import math
print (math.sqrt(16))
# Import only the sqrt function from the math package
from math import sqrt
print(sqrt(25))


4.0
5.0


In [8]:
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [10]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [11]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
c = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=complex)
c

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [ ]:
a.shape
a.ndim

2

In [ ]:
a.dtype.name

'int64'

In [ ]:
a.size


15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.array([20, 30, 40, 50])
print(a)
b = np.arange(4)
print(b)
c=a-b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [ ]:
a = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
a = a[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", a)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]
